{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "98504e53-ee1d-48a6-98b8-a0f7def3a2cb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import urllib.parse\n",
    "\n",
    "# 1. Configuration\n",
    "YOUR_PHONE_NUMBER = \"919821352868\"  # REPLACE WITH YOUR WHATSAPP NUMBER (with country code, no +)\n",
    "COMPANY_NAME = \"SIPAURA DRINKWARE\"\n",
    "\n",
    "st.set_page_config(page_title=COMPANY_NAME, layout=\"wide\", page_icon=\"🥤\")\n",
    "\n",
    "# Custom CSS for a professional look\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .stButton>button {\n",
    "        background-color: #25D366;\n",
    "        color: white;\n",
    "        border-radius: 8px;\n",
    "        border: none;\n",
    "        font-weight: bold;\n",
    "    }\n",
    "    .stButton>button:hover {\n",
    "        background-color: #128C7E;\n",
    "        color: white;\n",
    "    }\n",
    "    .product-card {\n",
    "        padding: 15px;\n",
    "        border-radius: 10px;\n",
    "        background-color: #f8f9fa;\n",
    "        margin-bottom: 20px;\n",
    "        border: 1px solid #e9ecef;\n",
    "    }\n",
    "    </style>\n",
    "\"\"\", unsafe_scale=True)\n",
    "\n",
    "# 2. Load and clean the Excel Data directly from \"Product catalogue.xlsx\"\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    # Skip the header titles and read the raw catalog\n",
    "    df = pd.read_excel(\"Product catalogue.xlsx\", sheet_name=\"Catalogue\", skiprows=5)\n",
    "    # Strip whitespace from column names\n",
    "    df.columns = df.columns.str.strip()\n",
    "    # Drop rows that don't have a valid SKU ID\n",
    "    df = df.dropna(subset=[\"SKU ID\"])\n",
    "    return df\n",
    "\n",
    "try:\n",
    "    df = load_data()\n",
    "except Exception as e:\n",
    "    st.error(\"Could not read 'Product catalogue.xlsx'. Make sure it is in the same folder as app.py.\")\n",
    "    st.stop()\n",
    "\n",
    "# 3. Sidebar Brand Header & Filters\n",
    "st.sidebar.title(f\"✨ {COMPANY_NAME}\")\n",
    "st.sidebar.markdown(\"---\")\n",
    "\n",
    "categories = [\"All\"] + list(df[\"Category\"].dropna().unique())\n",
    "selected_category = st.sidebar.selectbox(\"Filter by Category\", categories)\n",
    "\n",
    "# Filter Data\n",
    "if selected_category != \"All\":\n",
    "    filtered_df = df[df[\"Category\"] == selected_category]\n",
    "else:\n",
    "    filtered_df = df\n",
    "\n",
    "# 4. Main Storefront App Navbar/Header\n",
    "st.title(f\"🥤 {COMPANY_NAME} Digital Storefront\")\n",
    "st.markdown(\"Browse our premium catalog below. Click any item to instantly send an enquiry via WhatsApp.\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# 5. Render Products Grid\n",
    "if filtered_df.empty:\n",
    "    st.warning(\"No products found.\")\n",
    "else:\n",
    "    # Use 3 columns layout\n",
    "    cols = st.columns(3)\n",
    "    \n",
    "    for index, row in filtered_df.iterrows():\n",
    "        # Handle missing prices natively since Selling Price is blank in the file\n",
    "        price_val = row.get(\"Selling Price\")\n",
    "        price_display = f\"₹{price_val}\" if pd.notna(price_val) else \"Contact for Price\"\n",
    "        \n",
    "        prod_name = row.get(\"Product Name\", \"Unnamed Product\")\n",
    "        sku = row.get(\"SKU ID\", \"N/A\")\n",
    "        capacity = row.get(\"Capacity\", \"N/A\")\n",
    "        colour = row.get(\"Colour\", \"N/A\")\n",
    "        specs = row.get(\"Specification\", \"Premium Insulated Build\")\n",
    "        if pd.isna(specs): specs = \"Premium Stainless Steel Insulated Bottle.\"\n",
    "\n",
    "        # Dynamic placeholder image (Can swap out with hosted links later)\n",
    "        placeholder_image = \"https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500\"\n",
    "\n",
    "        with cols[index % 3]:\n",
    "            st.markdown('<div class=\"product-card\">', unsafe_allow_html=True)\n",
    "            st.image(placeholder_image, use_container_width=True)\n",
    "            st.markdown(f\"### {prod_name}\")\n",
    "            st.markdown(f\"**SKU:** `{sku}`\")\n",
    "            st.markdown(f\"**Specs:** {capacity} | {colour}\")\n",
    "            st.markdown(f\"💰 **Price:** **{price_display}**\")\n",
    "            st.caption(f\"_{specs}_\")\n",
    "            \n",
    "            # Construct clear WhatsApp pre-filled message format\n",
    "            msg = f\"Hi {COMPANY_NAME}! I would like to enquire about:\\n\\n\" \\\n",
    "                  f\"📦 *Product:* {prod_name}\\n\" \\\n",
    "                  f\"🆔 *SKU:* {sku}\\n\" \\\n",
    "                  f\"📏 *Capacity:* {capacity}\\n\" \\\n",
    "                  f\"🎨 *Colour:* {colour}\\n\" \\\n",
    "                  f\"💸 *Price:* {price_display}\"\n",
    "                  \n",
    "            encoded_msg = urllib.parse.quote(msg)\n",
    "            wa_link = f\"https://wa.me/{YOUR_PHONE_NUMBER}?text={encoded_msg}\"\n",
    "            \n",
    "            st.link_button(\"💬 Send WhatsApp Enquiry\", wa_link, use_container_width=True)\n",
    "            st.markdown('</div>', unsafe_allow_html=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
